### PR TITLE
Yo API Upgrade

### PR DESCRIPTION
**Pull request by BuKinoshita**

### CODE REVIEW

**Comment by BuKinoshita** [comment]
#7

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Just released a new tag on GitHub and npm!

**Comment by zenorocha** [comment]
Also added you as a contributor since I'm not maintaining this project anymore.

Feel free to improve it as you like ;)

**Comment by BuKinoshita** [comment]
Ty

**Pull request merged**
